### ISSUE TITLE
v2.4.7 打不开

### ISSUE THREAD

**Issue by ZengTianShengZ** [fylz1125/CCFish#2]
现在 cocos creator 是2.4.7 版本，最低的也是 2.3.2 ，打不开该游戏。

<img width="900" alt="image" src="https://user-images.githubusercontent.com/15622519/154788973-23bdbed1-04ba-4abe-af00-efa60f9072d2.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/15622519/154789025-831b021f-e434-4d9e-8eb4-9fdcbf3eba85.png">

**Comment by DJReact** [comment]
同样问题

**Comment by fylz1125** [comment]
没有维护2.4版本，2.4的材质系统跟2.0差异很大，打不开很正常的
